version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/preInstall-pacakges.sh
      timeout: 300
      runas: root
    - location: scripts/preInstall-dbinit.sh
      timeout: 300
      runas: root
    - location: scripts/install-wordpress.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/wordpress-setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
